version: "2.23.0-desktop.1"

services:
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shop
    ports:
      - "3306:3306"
    volumes:
      - shop_db_data:/var/lib/shop
    networks:
      - network_shop

  shop:
    container_name: shop
    restart: always
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/shop
    networks:
      - network_shop
volumes:
  shop_db_data:
networks:
  network_shop: